<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png" width="300" alt="cognitiveclass.ai logo"  />
</center>

# **Data Visualization Lab**

Estimated time needed: **45 to 60** minutes

In this assignment you will be focusing on the visualization of data.

The data set will be presented to you in the form of a RDBMS.

You will have to use SQL queries to extract the data.

## Objectives

In this lab you will perform the following:

*   Visualize the distribution of data.

*   Visualize the relationship between two features.

*   Visualize composition of data.

*   Visualize comparison of data.

<hr>

## Demo: How to work with database

Download database file.

In [ ]:
!wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m4_survey_data.sqlite

Connect to the database.

In [ ]:
import sqlite3
conn = sqlite3.connect("m4_survey_data.sqlite") # open a database connection

Import pandas module.

In [ ]:
import pandas as pd

## Demo: How to run an sql query

In [ ]:
# print how many rows are there in the table named 'master'
QUERY = """
SELECT COUNT(*) 
FROM master"""
# the read_sql_query runs the sql query and returns the data as a dataframe
df = pd.read_sql_query(QUERY,conn)
df.head()

## Demo: How to list all tables

In [ ]:
# print all the tables names in the database
QUERY = """
SELECT name as Table_Name FROM
sqlite_master WHERE
type = 'table'
"""
# the read_sql_query runs the sql query and returns the data as a dataframe
pd.read_sql_query(QUERY,conn)

## Demo: How to run a group by query

In [ ]:
QUERY = """
SELECT Age,COUNT(*) as count
FROM master
group by age
order by age
"""
pd.read_sql_query(QUERY,conn)

## Demo: How to describe a table

In [ ]:
table_name = 'master'  # the table you wish to describe

QUERY = """
SELECT sql FROM sqlite_master
WHERE name= '{}'
""".format(table_name)

df = pd.read_sql_query(QUERY,conn)
print(df.iat[0,0])

# Hands-on Lab

## Visualizing distribution of data

### Histograms

Plot a histogram of `ConvertedComp.`

In [ ]:
# your code goes here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
df = pd.read_csv("https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DA0321EN-SkillsNetwork/LargeData/m2_survey_data.csv")

df = pd.read_sql_query("SELECT * FROM master", conn)
df

plt.figure(figsize=(10,5))
sns.distplot(a=df["ConvertedComp"],bins=20,kde=False)
plt.show()

### Box Plots

Plot a box plot of `Age.`

In [ ]:
# your code goes here

df = pd.read_sql_query("SELECT * FROM master", conn)
df

plt.figure(figsize=(10,5))
sns.boxplot(x=df.ConvertedComp, data=df)
plt.show()

## Visualizing relationships in data

### Scatter Plots

Create a scatter plot of `Age` and `WorkWeekHrs.`

In [ ]:
# your code goes here

QUERY = """

SELECT Age,ConvertedComp,WorkWeekHrs,CodeRevHrs,MainBranch

FROM master

"""

df=pd.read_sql_query(QUERY,conn)

df

df.plot(kind='scatter', x='Age', y='WorkWeekHrs', figsize=(10, 6), color='darkblue')

### Bubble Plots

Create a bubble plot of `WorkWeekHrs` and `CodeRevHrs`, use `Age` column as bubble size.

In [ ]:
# your code goes here
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

QUERY = """

SELECT Age,WorkWeekHrs,CodeRevHrs 

FROM master

"""

df=pd.read_sql_query(QUERY,conn)

df
plt.style.use('ggplot')
plt.scatter('WorkWeekHrs', 'CodeRevHrs', s='Age',alpha=0.5, data=df)
plt.xlabel("WorkWeekHrs", size=16)
plt.ylabel("CodeRevHrs", size=16)

## Visualizing composition of data

### Pie Charts

Create a pie chart of the top 5 databases that respondents wish to learn next year. Label the pie chart with database names. Display percentages of each database on the pie chart.

In [ ]:
# your code goes here

QUERY = """

select count(DatabaseDesireNextYear) as Count,DatabaseDesireNextYear from DatabaseDesireNextYear 
group by DatabaseDesireNextYear order by count(DatabaseDesireNextYear) DESC LIMIT 5

"""

df2=pd.read_sql_query(QUERY,conn)

df2.set_index('DatabaseDesireNextYear',inplace=True)

df2 

df2=pd.read_sql_query(QUERY,conn)

labels ='PosgreSQL', 'MongoDB','Redis', 'MySQL', 'Elasticsearch'
size=df2.set_index('DatabaseDesireNextYear',inplace=True)

sizes=df2.iloc[:,0]

plt.pie(sizes, labels=labels, startangle=90, shadow=True, explode=(0.1, 0.1, 0.1, 0.1, 0.1), autopct='%1.2f%%')

plt.title('Top 5 Databases')

plt.show()

### Stacked Charts

Create a stacked chart of median `WorkWeekHrs` and `CodeRevHrs` for the age group 30 to 35.

In [ ]:
# your code goes here
QUERY = """

SELECT WorkWeekHrs, CodeRevHrs, Age FROM master where Age between 30 and 35

"""
df_master2=pd.read_sql_query(QUERY,conn)
df_master2.head(5)

df_grouped = df_master2.groupby(df_master2.Age)[['WorkWeekHrs', 'CodeRevHrs']].median()
df_grouped.head()

df_grouped.plot(kind='bar',stacker=True)
plt.title ("Median WorkWeekHours and CodeRevHrs by Age")
plt.xlabel("Age")

plt.show()

## Visualizing comparison of data

### Line Chart

Plot the median `ConvertedComp` for all ages from 45 to 60.

In [ ]:
# your code goes here

### Bar Chart

Create a horizontal bar chart using column `MainBranch.`

In [ ]:
# your code goes here

Close the database connection.

In [ ]:
conn.close()

## Authors

Ramesh Sannareddy

### Other Contributors

Rav Ahuja

## Change Log

| Date (YYYY-MM-DD) | Version | Changed By        | Change Description                 |
| ----------------- | ------- | ----------------- | ---------------------------------- |
| 2020-10-17        | 0.1     | Ramesh Sannareddy | Created initial version of the lab |

Copyright © 2020 IBM Corporation. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDA0321ENSkillsNetwork21426264-2021-01-01&cm_mmc=Email_Newsletter-\_-Developer_Ed%2BTech-\_-WW_WW-\_-SkillsNetwork-Courses-IBM-DA0321EN-SkillsNetwork-21426264&cm_mmca1=000026UJ&cm_mmca2=10006555&cm_mmca3=M12345678&cvosrc=email.Newsletter.M12345678&cvo_campaign=000026UJ).